<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2182" started-at="2019-11-10T19:55:33Z" finished-at="2019-11-10T19:55:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2182" started-at="2019-11-10T19:55:33Z" finished-at="2019-11-10T19:55:35Z">
      <class name="com.automation.testCases.ManagerLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.automation.testCases.ManagerLoginTest@1ce92674]" name="setUp" is-config="true" duration-ms="18696" started-at="2019-11-11T01:25:14Z" finished-at="2019-11-11T01:25:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="bankManagerLogin()[pri:0, instance:com.automation.testCases.ManagerLoginTest@1ce92674]" name="bankManagerLogin" duration-ms="2161" started-at="2019-11-11T01:25:33Z" finished-at="2019-11-11T01:25:35Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Cannot find elements when the XPath is null.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
	at org.openqa.selenium.By$ByXPath.<init>(By.java:339)
	at org.openqa.selenium.By.xpath(By.java:92)
	at com.automation.testCases.ManagerLoginTest.bankManagerLogin(ManagerLoginTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bankManagerLogin -->
        <test-method status="PASS" signature="setDown()[pri:0, instance:com.automation.testCases.ManagerLoginTest@1ce92674]" name="setDown" is-config="true" duration-ms="755" started-at="2019-11-11T01:25:35Z" finished-at="2019-11-11T01:25:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDown -->
      </class> <!-- com.automation.testCases.ManagerLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
